version: "3.8"

services:
  # Banco de Dados PostgreSQL
  db:
    image: postgres:15
    container_name: linkhub_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: linkhub
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
