version: "3.8"

services:
  app:
    build: .
    container_name: linkhub_app
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DB_SSL=false
      - SESSION_SECURE=false
      - PORT=5000
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=linkhub
      - SESSION_SECRET=segredo_muito_secreto_mude_isso
      - FRONTEND_URL=http://localhost:5000
      # Adicione suas chaves de API aqui ou em um arquivo .env
      # - GOOGLE_CLIENT_ID=...
      # - GOOGLE_CLIENT_SECRET=...
      # - GITHUB_CLIENT_ID=...
      # - GITHUB_CLIENT_SECRET=...
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres:15
    container_name: linkhub_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: linkhub
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: